# hydra config
hydra:
  run:
    dir: /workspace/code/logs/prepare_dataset/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: false

YOLO:
  pose_ckpt: "/workspace/code/ckpt/yolo11x-pose.pt"
  seg_ckpt: "/workspace/code/ckpt/yolo11x-seg.pt"
  bbox_ckpt: "/workspace/code/ckpt/yolo11x.pt"
  conf: 0.8
  iou: 0.5
  verbose: False
  device: 1
  img_size: 640
  save_path: "/workspace/data/vis"

depth_estimator:
  dpt_processor_path: "/workspace/code/ckpt/"
  dpt_model_path: "/workspace/code/ckpt/"

  model: Intel/dpt-large
  device: 1
  save_path: "/workspace/data/depth"

# Path
# use YOLOv11 detection with tracking.
extract_dataset:
  data_path: "/workspace/data/raw" # this is raw data path.
  save_path: "/workspace/data/" # this is extracted video path.

OF: false

batch_size: 20